Repository konveyor/crane-runner, pull requests merged in 2022-07, with the labels that each got.

#51 chore(workflows): configure actions after updates
  .github/workflows/needs-triage.yaml
  .github/workflows/reconcile_gh_issue.yaml
Labels: approved

#52 Fix plugin install
  Dockerfile
Labels: lgtm, approved

#53 feat(tasks): Add registry info task
  config/clustertasks/kustomization.yaml
  config/clustertasks/oc-registry-info.yaml
Labels: lgtm, approved

#60 feat(tasks): add image-sync task
  Dockerfile
  config/clustertasks/crane-image-sync.yaml
  config/clustertasks/kustomization.yaml
  config/clustertasks/oc-registry-info.yaml
Labels: lgtm, approved

#61 chore(tasks): set bash optionals for better debug
  config/clustertasks/crane-apply.yaml
  config/clustertasks/crane-export.yaml
  config/clustertasks/crane-kubeconfig-generator.yaml
  config/clustertasks/crane-kubectl-scale-down.yaml
  config/clustertasks/crane-kustomize-init.yaml
  config/clustertasks/crane-transfer-pvc.yaml
  config/clustertasks/crane-transform.yaml
  config/clustertasks/kubectl-apply-files.yaml
  config/clustertasks/kubectl-apply-kustomize.yaml
Labels: lgtm, approved

#64 Add `verify` param to crane-transfer-pvc ClusterTask
  config/clustertasks/crane-transfer-pvc.yaml
Labels: lgtm, approved

#65 chore(registry-info): enable silent failure
  config/clustertasks/oc-registry-info.yaml
Labels: lgtm, approved, do-not-merge/hold

#62 chore(tasks): parameterize tls-verify params to skopeo
  config/clustertasks/crane-image-sync.yaml
  config/clustertasks/crane-transform.yaml
Labels: lgtm, approved
